### ISSUE TITLE
UC CRUD Imballo

### ISSUE THREAD

**Issue by luca-lezzerini** [luca-lezzerini/ecomm-jpr-02#10]
Creare UC CRUD server + client per entità Imballo.
e-commerce.CRUD
e-commerce.Entità.Entità

**Comment by luca-lezzerini** [comment]
Apritevi ticket interni per gestire la ripartizione del lavoro del gruppo

**Comment by Francesco-bit** [comment]
Lato server, in lavorazione. Commit f9195dd006d60c69d49cd56f64aa9ff641299fb3

**Comment by Giuseppe211** [comment]
lato client, creato il component imballo. Commit f80ead1b15b0bd31e579324c2b424697833e8b0e

**Comment by Francesco-bit** [comment]
Commentato codice per ricercaByCosto. Commit ddc00d610899e462f58f8bb007ed05a755ae8aa2

**Comment by Giuseppe211** [comment]
completati gli stati "visualizza", "ricerca", "aggiungi", "modifica", "conferma". Commit f962b8a02d216f44e8e6cf8bb8eaf3addcef4950

**Comment by Francesco-bit** [comment]
Modifiche a seguito test. Commit 3696f362258d6fa5dc192efe41058cde1a59cff0

**Comment by Tizioincognit0** [comment]
Completato con commit f3684139591eae3bd8089efcbb8ef980c3a0ae40.

**Comment by Tizioincognit0** [comment]
Completato con commit f3684139591eae3bd8089efcbb8ef980c3a0ae40.
