### ISSUE TITLE
Implementare UC Associazione Prodotto con Colore

### ISSUE THREAD

**Issue by luca-lezzerini** [luca-lezzerini/ecomm-jpr-02#101]

**Comment by Tizioincognit0** [comment]
Aggiunta associazione a “Colore.java” con commit 1e0d3830e9d1a5e6847c4c240022458e27692858.

**Comment by Tizioincognit0** [comment]
Aggiunta associazione OneToMany a “Colore.java” con commit 1e0d383.

**Comment by Tizioincognit0** [comment]
Creata interfaccia utente "associa-colore” con commit f31416dd31c71e0c02552e1ee57e0500cbc493b7.

**Comment by Tizioincognit0** [comment]
Creato service di "associa-colore" lato client con commit 7833a48c2adcf5c31603ed030bf221d7512b05d0.

**Comment by Tizioincognit0** [comment]
I problemi lato server sono stati risolti ed ho potuto effettuare dei test comprendenti entrambi i lati. Da essi sono emerse alcune imperfezioni corrette nei commit 509ecd3823164fe7c75f4a59df1a0f75977047a3, a6151342251825d290bf1d0a64fed79ad2735c26 e 7948535da0e3d775b8eb6fd5796281dd93658b2e. L’interfaccia utente visualizza i dati e si comporta come richiesto nelle specifiche ma, a causa di quanto detto nel mio precedente commento, l’associazione ancora non funziona.

**Comment by Tizioincognit0** [comment]
Teoricamente ho terminato l’associazione con commit 36efe772b2ac2e237967a5a5e9f7c922b9709100 tuttavia, per permettere al server di eseguire l’associazione, ho dovuto aggiungere alla classe client “prodotto.ts” l’attributo “colore” di tipo “Colore”. A seguito dei test effettuati, ho appurato il corretto funzionamento dell’associazione ma non mi è possibile committare al momento le modifiche apportate a “prodotto.ts”. Dunque, per il momento, sarà possibile effettuare l’associazione solo sulla mia macchina.

**Comment by Tizioincognit0** [comment]
Apportate modifiche lato client a "associa-colore.service.ts" con commit f1b1c1e3c77452b78401b6902446fdf9ebadffc1 su suggerimento del docente @luca-lezzerini. Ora i metodi già realizzati negli altri service non sono più copiati e incollati bensì iniettati.

**Comment by Tizioincognit0** [comment]
Modifica a "prodotto.ts" autorizzata con ticket #110. Ora l'associazione dovrebbe funzionare per tutti. Lascio questa issue aperta poiché potrebbero essere necessari dei miglioramenti.

**Comment by Tizioincognit0** [comment]
Apportate modifiche lato client a "associa-colore.service.ts" con commit 4d0775f77bb3f1dfe10d30de00c851758e8b08fd per  correggere degli errori dovuti a chiamate asincrone.
