### ISSUE TITLE
Implementare UC Associazione Prodotto con Taglia

### ISSUE THREAD

**Issue by luca-lezzerini** [luca-lezzerini/ecomm-jpr-02#104]

**Comment by Simoneval22** [comment]
Taglia modificata 27b249e5ad2d8227df377f25316d794214b35292

**Comment by Tizioincognit0** [comment]
Terminata con commit https://github.com/luca-lezzerini/ecomm-jpr-02/commit/ada06c656b430fd9aa03d214b8d73caefc2ebdce.
