### ISSUE TITLE
Creazione cartella Associazioni lato client

### ISSUE THREAD

**Issue by CatiaNiccolai** [luca-lezzerini/ecomm-jpr-02#105]
Creare la cartella Associazioni sul client dove collocare le interfacce Associa-entità

**Comment by Bobanalist** [comment]
fatto 6b09eba12f4673447223e0f5c37acb27ef51ab16

**Comment by Tizioincognit0** [comment]
La cartella in realtà non è stata creata.

**Comment by Tizioincognit0** [comment]
Cartella creata con commit ee7806ff2b908bb889dfa335f492caae0ac84d2a.
