### ISSUE TITLE
UC CRUD Colori

### ISSUE THREAD

**Issue by luca-lezzerini** [luca-lezzerini/ecomm-jpr-02#11]
Creare UC CRUD server + client per entità Colore.
e-commerce.CRUD
e-commerce.Entità.Entità

**Comment by Ramello83** [comment]
lo stiamo facendo

**Comment by Ramello83** [comment]
Parte server completata da rivedere.

**Comment by Tizioincognit0** [comment]
Parte server rivista senza effettuare modifiche.

**Comment by Ramello83** [comment]
Parete client completata 8c456d1ace9064d85aa90f8c1d5ccc6347c76fd9

**Comment by Ramello83** [comment]
Server e Client testati e funzionanti chiudo il ticket

**Comment by Ramello83** [comment]
mancano alcuni dettagli su ricerca (impedire ricerca senza valore e cambiare metodo al serve colorelike)

**Comment by Ramello83** [comment]
Completato. Aggiunto service nel client Testato e tutto funzionante. Chiudo in attesa che venga riaperto con nuove e più dettagliate specifiche, o anche con critiche costruttive e consigli sempre ben accettati
