### ISSUE TITLE
Richiesta inserimento Route

### ISSUE THREAD

**Issue by gianmarcopetrillo** [luca-lezzerini/ecomm-jpr-02#111]
Devo inserire la mia route(associa-offerta), è stata dimenticata in precedenza, e aggiunta di AssociaOffertaComponent nell app.module.ts

**Comment by CatiaNiccolai** [comment]
autorizzato

**Comment by gianmarcopetrillo** [comment]
8b933a1bf57e1c3bc1341c127afae1119a3b58f5
