### ISSUE TITLE
UC CRUD Categoria

### ISSUE THREAD

**Issue by luca-lezzerini** [luca-lezzerini/ecomm-jpr-02#12]
Creare UC CRUD server + client per entità Categoria.
e-commerce.CRUD
e-commerce.Entità.Entità

**Comment by luca-lezzerini** [comment]
Apritevi ticket interni per gestire la ripartizione del lavoro nel gruppo

**Comment by Bobanalist** [comment]
commit CategoriaCRUD, rimangono da gestire solo eccezioni. 48599bf62c422fdbb607077dcf626bc6f13fb3b6

**Comment by Tizioincognit0** [comment]
Terminato con commit https://github.com/luca-lezzerini/ecomm-jpr-02/commit/0d90990012bd9239c164355ce2ec1ae81ca75709.
