### ISSUE TITLE
Configurare app.module.ts

### ISSUE THREAD

**Issue by luca-lezzerini** [luca-lezzerini/ecomm-jpr-02#14]
Aggiungere
FormsModule
HttpClient

**Comment by Bobanalist** [comment]
Fatto.
Installate librerie node_modules.
Configurati HttpClient e FormsModule.

**Comment by luca-lezzerini** [comment]
Manca l'SHA del commit

**Comment by Bobanalist** [comment]
Su GitHub Desktop non riusciamo a prendere quel codice
