### ISSUE TITLE
Creare Entity colori

### ISSUE THREAD

**Issue by Ramello83** [luca-lezzerini/ecomm-jpr-02#17]
Creare nel packcage modell l'entità colore

**Comment by luca-lezzerini** [comment]
Bene, ottimo! Suddividere il lavoro tramite ticket è una delle cose che dovevate scoprire.
Bravi!

**Comment by Ramello83** [comment]
Scoprire "ce" lo sta dicendo da natale scorso!!!!!!!ahahaha

**Comment by Ramello83** [comment]
codi SHA 3550b8f963ac8c9753cbbac4b0f316d508acd769
