### ISSUE TITLE
Colloquio con lo Stakeholder Lezzerini.

### ISSUE THREAD

**Issue by Ramello83** [luca-lezzerini/ecomm-jpr-02#2]
Per poter continuare scendendo più nello specifico, nell'analizzare i processi di business necessitiamo di parlare con i dirigenti della azienda.

**Comment by luca-lezzerini** [comment]
Va bene, tra pochi minuti ci parlerà.

**Comment by luca-lezzerini** [comment]
Colloquio avvenuto alle 11:30
