### ISSUE TITLE
Lato server imballo

### ISSUE THREAD

**Issue by Francesco-bit** [luca-lezzerini/ecomm-jpr-02#25]
CRUD imballo in lavorazione

**Comment by Francesco-bit** [comment]
Commit f9195dd006d60c69d49cd56f64aa9ff641299fb3

**Comment by Francesco-bit** [comment]
Update ServiceImballo. Commit f0af52d2c7ee2cdfb4e3d8e6fdcc0aec42b7ca8c

**Comment by Francesco-bit** [comment]
Completato. Commit 11c9bc3cd7a2bb80c39991455617d1b5d52f9433

**Comment by Francesco-bit** [comment]
Riaperta lavorazione. Commit dc599c6b32f2328f8ddd2436db7fcad467b7c7b0

**Comment by Francesco-bit** [comment]
Fase di test. Commit 4c2e5b2b7da718286591fcbabba5c01593b16a97

**Comment by Francesco-bit** [comment]
Avanzamento fase test Imballo. Commit 62822cbede320365bbdcca2a0b45962c06f344c1

**Comment by Francesco-bit** [comment]
modifche ImballoDto. Commit 988bd68054d9844c0c05543b1d32ba12538b0ae1

**Comment by Francesco-bit** [comment]
Avanzamento test. Modifiche lato server e lato client. Commit 83e2c7c444c70389cfb0e3a4ba9ba433116c3af4

**Comment by Francesco-bit** [comment]
Modifiche DTO. Commit 3b0f46d0305b0f4384493b4f643d0f9974738b7d

**Comment by Tizioincognit0** [comment]
Completato con commit f3684139591eae3bd8089efcbb8ef980c3a0ae40.
