### ISSUE TITLE
Merge in corso su ServiceColori: risolvere perché blocca il lavoro

### ISSUE THREAD

**Issue by luca-lezzerini** [luca-lezzerini/ecomm-jpr-02#27]
Merge in corso su ServiceColori: risolvere perché blocca il lavoro

**Comment by gianmarcopetrillo** [comment]
Sto provando  a rimuoverlo ma probabilmente sto facendo peggio

**Comment by luca-lezzerini** [comment]
Novità?

**Comment by gianmarcopetrillo** [comment]
Per adesso sembra funzionare tutto, ma non ho la certezza di aver sistemato/fermato il merge..

**Comment by luca-lezzerini** [comment]
Ok, domani verifico io, mi assegna il ticket per favore?Sent from my Wiko W_C860Il 03 ago 2020 21:38, gianmarcopetrillo <notifications@github.com> ha scritto:
Per adesso sembra funzionare tutto, ma non ho la certezza di aver sistemato/fermato il merge..

**Comment by luca-lezzerini** [comment]
Se il merge non c'è più chiuda il ticket, per favore
