### ISSUE TITLE
Proposta cartelle Angular 

### ISSUE THREAD

**Issue by Ramello83** [luca-lezzerini/ecomm-jpr-02#29]
Propongo di fare tre cartelle:
Component-colori
Component_categoria
Component-imballo
e mettere i vari component dentro
Più una cartella service
Spero che @Frasr99 e @BobAnalist siano d’accordo.

**Comment by luca-lezzerini** [comment]
Non sono @Frasr99 e @Bobanalist che decidono, ma decido io (@luca-lezzerini).
@CatiaNiccolai viene nominata, sul campo, Responsabile del controllo di configurazione. La creazione di qualsiasi cartella lato client e lato server deve essere autorizzata da lei, previa apertura ticket e assegnazione a lei.
Il Responsabile di Configurazione decide il nome, la posizione e il contenuto delle cartelle definite ma non le crea: la creazione è demandata al richiedente. Il tutto deve essere autorizzato via ticket.
Procedura da seguire:
Tizio apre ticket e lo assegna al RdC proponendo nome cartella, posizione e contenuto. RdC analizza il ticket e, cercando di mantenere un criterio uniforme di naming, accetta o modifica la richiesta (o la rigetta se già esistono cartelle destinate allo scopo). Scrive la decisione nel ticket e lo riassegna a Tizio, che esegue, committa e chiude.

**Comment by luca-lezzerini** [comment]
@Ramello83 per favore comunichi a tutti i team dell'Aula 2 che Niccolai è stata nominata RdC (Responsabile del controllo di Configurazione)

**Comment by Ramello83** [comment]
sarà fatto!

Il giorno lun 3 ago 2020 alle ore 21:22 luca-lezzerini <
notifications@github.com> ha scritto:

**Comment by Ramello83** [comment]
chiudo
