### ISSUE TITLE
Progetto JPR2.zip su Moodle

### ISSUE THREAD

**Issue by CatiaNiccolai** [luca-lezzerini/ecomm-jpr-02#3]
Il file è in formato eapx, è possibile averlo in eap?

**Comment by luca-lezzerini** [comment]
Proverò ad esportarlo in XMI

**Comment by luca-lezzerini** [comment]
Caricato JPR2-XMI con xml (usare funzione di import XML / XMI 2.x).
Caricato JPR2-HTML con versione HTML.
