### ISSUE TITLE
Progettazione Home Page

### ISSUE THREAD

**Issue by luca-lezzerini** [luca-lezzerini/ecomm-jpr-02#30]
Progettare home page

**Comment by Bobanalist** [comment]
In lavorazione.
In attesa di direttive a riguardo.
Creazione home + Redirect in app.module.ts

**Comment by Ramello83** [comment]
Visto che nel home bisogna gestire i prodotti aprirò un ticket per una proposta e chiarimenti poi possiamo vederlo insieme

**Comment by Tizioincognit0** [comment]
Progettazione conclusa con commit d6bb9a95fd21a11ddb14a3f9095f5e59a10fcad7.
