### ISSUE TITLE
Proposta Cartelle Angular

### ISSUE THREAD

**Issue by Ramello83** [luca-lezzerini/ecomm-jpr-02#31]
Letto la mail il ticket in ritardo noi abbiamo fatto cartella 
Component-Colore: contente i seguenti component
-colore-crud
-dati-colore
-lista-colore
-ricerca-colore
Propongo di continuare così, ma possiamo modificare.
Propongo di fare una unica cartella dei service.

**Comment by luca-lezzerini** [comment]
Continuate così ma Nicolai è RdC e quindi da adesso in poi tocca a leiSent from my Wiko W_C860Il 03 ago 2020 21:39, Ramello83 <notifications@github.com> ha scritto:

Letto la mail il ticket in ritardo noi abbiamo fatto cartella

Component-Colore: contente i seguenti component

-colore-crud

-dati-colore

-lista-colore

-ricerca-colore

Propongo di continuare così, ma possiamo modificare.

Propongo di fare una unica cartella dei service.

**Comment by CatiaNiccolai** [comment]
Letto, ritengo chiusa la questione entityCrudComponent.
Seguirà ticket per Service
