### ISSUE TITLE
Sistemazione Merge

### ISSUE THREAD

**Issue by gianmarcopetrillo** [luca-lezzerini/ecomm-jpr-02#32]
Sistemazione del merge branch in corso

**Comment by luca-lezzerini** [comment]
Per risolvere il merge in maniera "spiccia" dovete fare così:
1) rinominare l'intera cartella di sviluppo (ossia la cartella dove avete clonato). Suggerisco di aggiungere.old al nome
2) clonare ex-novo da repository
3) aggiungere le librerie angular con npm i @angular/cli
4) copiare o modificare i file clonati che erano cambiati e si trovano nella .old
5) committare
6) eliminare la cartella .old

**Comment by Tizioincognit0** [comment]
Risolto con commit 7b70eb9ece451d746c3ef151a38c5280dd2b6b87.
