### ISSUE TITLE
Fare service colori

### ISSUE THREAD

**Issue by Ramello83** [luca-lezzerini/ecomm-jpr-02#35]
Fare service colori

**Comment by Tizioincognit0** [comment]
Lato server o lato client?

**Comment by Tizioincognit0** [comment]
Alla fine è stato deciso di non creare un service colori lato client dunque chiudo.

**Comment by Tizioincognit0** [comment]
Alla fine è stato deciso di non creare un service colori lato client dunque chiudo.

**Comment by Tizioincognit0** [comment]
Alla fine è stato deciso di non creare un service colori lato client dunque chiudo.

**Comment by Tizioincognit0** [comment]
Alla fine è stato deciso con nuove direttive di non creare un service colori lato client dunque chiudo.
