### ISSUE TITLE
completare il lato client Imballo

### ISSUE THREAD

**Issue by Giuseppe211** [luca-lezzerini/ecomm-jpr-02#37]
In lavorazione. Commit 63d899801c9a6124c0eceb3d04162dbcbc488d53

**Comment by Giuseppe211** [comment]
aggiornamento. Commit 7d2206e710fc8d9e2f8090bf09cdea60bd0ed994

**Comment by Francesco-bit** [comment]
Problema sollevato nel ticket #39

**Comment by Francesco-bit** [comment]
apportate modifiche per ticket #39. Commit 55e475ff3ab9cebf4adbb4528c754e035550c8ce

**Comment by Francesco-bit** [comment]
Modifiche ImballoDto. Commit 2bd5d7803080583c96a3ae690e353ff3529ab1cb

**Comment by Francesco-bit** [comment]
Avanzamento test. Modifiche lato server e client. Commit 83e2c7c444c70389cfb0e3a4ba9ba433116c3af4

**Comment by Francesco-bit** [comment]
Formattazione codice. Commit 2f08149e4ad585d748dddd8e652d0d2d0c3bda77

**Comment by Francesco-bit** [comment]
Modifiche all`interfaccia. Commit 49f3c8716c932e8368ddc7ef83cd87a96195713e

**Comment by Tizioincognit0** [comment]
Corretto errore logico con commit: https://github.com/luca-lezzerini/ecomm-jpr-02/commit/f85e78f7014c61de39c3a6896ce4e705e569eb54.

**Comment by Tizioincognit0** [comment]
Terminato con commit https://github.com/luca-lezzerini/ecomm-jpr-02/commit/8af6d206c255a6a77d1af9562239e92aac4933d5.
