### ISSUE TITLE
Bisogna sistemare il routing 

### ISSUE THREAD

**Issue by Ramello83** [luca-lezzerini/ecomm-jpr-02#38]
devo inserire il path colori e imballo è scritto con la I maiuscola potrebbe dare problemi.  e il redirect dovrebbe puntare ad una pagina home generica.

**Comment by Ramello83** [comment]
inserita rout colori 9dba213c8d28fc8d17b60ef599f9663887c44286

**Comment by Ramello83** [comment]
Sistemare la redirect possiamo usare le url su la barra degli indirizzi per vedere i nostri progetti fino a quando non ci sarà una home. Continuano ad esserci problemi con imballo. Apro ticket.

**Comment by CatiaNiccolai** [comment]
Scaricato adesso l'app-routing.moduls aggiornato, mi pare che i path per le tre entità siano tutti corretti.
per il redirectTo alla pagina generica apro un ticket subito a Badessi.

**Comment by Bobanalist** [comment]
Creta home generica e sistemato redirect
575958515154ea42ad2fd49a92abf725e038196a
