### ISSUE TITLE
Problemi con componet Imballo

### ISSUE THREAD

**Issue by Ramello83** [luca-lezzerini/ecomm-jpr-02#39]
Manca nel app-modules.ts in declarations la dichiarazione del component. 
nel app-routing.module.ts la url con la i piccola e non grande.

**Comment by Francesco-bit** [comment]
modifiche apportate. Commit 55e475ff3ab9cebf4adbb4528c754e035550c8ce

**Comment by Ramello83** [comment]
perfetto funziona tutto la console di crome non da più problemi chiudo il ticket
