### ISSUE TITLE
app-routing-module.ts

### ISSUE THREAD

**Issue by CatiaNiccolai** [luca-lezzerini/ecomm-jpr-02#41]
Bisogna correggere il redirect di seguito riportato:
{ path: '', redirectTo: '/categoria-crud', pathMatch: 'full'}
Il reindirizzamento deve essere verso la home, ma dal momento che non abbiamo ancora una home puoi predisporlo e lasciarlo commentato

**Comment by Bobanalist** [comment]
In lavorazione

**Comment by Bobanalist** [comment]
Aggiornato e chiudo
575958515154ea42ad2fd49a92abf725e038196a
