### ISSUE TITLE
Proposta User interface negli scenario ricerca e visualizza.

### ISSUE THREAD

**Issue by Ramello83** [luca-lezzerini/ecomm-jpr-02#42]
Allego immagine della proposta. 
![proposta](https://user-images.githubusercontent.com/67779342/89345053-23662280-d6a7-11ea-96a3-6e83ed0a634d.png)

**Comment by luca-lezzerini** [comment]
Grazie per la proposta ma devo respingerla. 
Il pulsante chiudi è superfluo: basta cliccare su un'altra riga o fare una ricerca e il form dati viene o chiuso o aggiornato.
La sua osservazione sarebbe corretta se avessimo aperto una finestra modale, ma in questo caso non viene accettata.
Grazie della collaborazione

**Comment by Ramello83** [comment]
ha chiuso e riaperto lo chiudo io. Comunque non so se abbiamo inteso in todo le specifiche. comunque colori è funzionate può vedere se la UI va bene o va cambiato qualcosa aspetterò i Ticket.
