### ISSUE TITLE
UC CRUD Anagrafica Prodotto

### ISSUE THREAD

**Issue by luca-lezzerini** [luca-lezzerini/ecomm-jpr-02#43]
UC CRUD Anagrafica Prodotto, come i precedenti

**Comment by gianmarcopetrillo** [comment]
Completato nel complesso, mancano solo piccole modifiche.(compilabile ed eseguibile)

**Comment by Ramello83** [comment]
Finito e testato con issue #62. Rimane aperto per provare nuovo metodo di ricerca.

**Comment by Ramello83** [comment]
Modificato Con @Query il metodo di ricerca bfb69bb9a1234a3fc27da395ea980df5a2681eb1
