### ISSUE TITLE
Implementare UC CRUD Gestione Archivio Taglie

### ISSUE THREAD

**Issue by luca-lezzerini** [luca-lezzerini/ecomm-jpr-02#44]
Implementare la gestione CRUD per l'entità Taglia.
e-commerce.CRUD
e-commerce.Entità.Anagrafiche.Anagrafiche

**Comment by Francesco-bit** [comment]
Pronto per test. Da implementare metodi di ricerca diversi da per sigla. Commit fe26c82e3d9cef49eb363082aceaac6b9794a7ad
