### ISSUE TITLE
UC CRUD Offerte

### ISSUE THREAD

**Issue by luca-lezzerini** [luca-lezzerini/ecomm-jpr-02#45]
Implementare la gestione CRUD per l'entità Offerta.
e-commerce.CRUD
e-commerce.Entità.Anagrafiche.Anagrafiche

**Comment by Giulio794** [comment]
Preso in carico

**Comment by Ramello83** [comment]
Entro in colaboarazione

**Comment by Giulio794** [comment]
Entita_offerta 6c05ca6387b88fb7ddd25310fbae53d6ea839e7d

**Comment by Giulio794** [comment]
Messo Service_Offerta 9a0734da10bd2960d4e79aefedba707ba146ee59

**Comment by Giulio794** [comment]
Completato 1a8e3aedc5f5fc52c063703aba894a1317afa075

**Comment by Giulio794** [comment]
Complatato Controller_offerta 4db2f711ef22777246c235f85ca296c393ef9fa5

**Comment by Giulio794** [comment]
rep e service aggiornati 361bdc6102afd58aa1eb09e49652dcfe279b1051

**Comment by Giulio794** [comment]
Completato template Offerta df30a338e3c26292844d8e35d9f12c8e2d131f0b

**Comment by Giulio794** [comment]
Dto Offerta Completato 82c095d25314cb6c2883980221c8257971a47254

**Comment by Giulio794** [comment]
Competato Compont offerta ma non funzionante 3864fda764101f5160216efec68f1ba3c34d8636

**Comment by Ramello83** [comment]
Sistemato e funzionante da rifinire 19b702c6e458119f7d95c34c6976593219820c7a

**Comment by Tizioincognit0** [comment]
Completato e testato lato client con commit 196a0ce8a5ad4567e08b7ea1a414640a94ca4386.

**Comment by Ramello83** [comment]
Chiuso con issue #63
