### ISSUE TITLE
UC CRUD Spedizioni

### ISSUE THREAD

**Issue by luca-lezzerini** [luca-lezzerini/ecomm-jpr-02#46]
Implementare la gestione CRUD per l'entità Spedizione.
e-commerce.CRUD
e-commerce.Entità.Anagrafiche.Anagrafiche

**Comment by Bobanalist** [comment]
Fatto, da testare non appena possibile. bfab934bdd9c7278ba541beb0afa2499ed2f35ae

**Comment by Bobanalist** [comment]
commit SpedizioneCRUD, rimangono da gestire solo eccezioni. 48599bf62c422fdbb607077dcf626bc6f13fb3b6
