### ISSUE TITLE
Creare Home Page

### ISSUE THREAD

**Issue by luca-lezzerini** [luca-lezzerini/ecomm-jpr-02#47]
e-commerce.Interfacce Utente.Home Page UI

**Comment by Bobanalist** [comment]
Home page impostata. In attesa di poter usufruire dei Prodotti.

**Comment by Ramello83** [comment]
Prodotti finiti facendo la injection del service prodotti nel component home. puoi usare lista srvP**.listaProdotti per la tabella.
mettere ne ngOinit della home il srvP**.lista() per richiamare i prodotti al caricamento della pagina.
Usare il metodo cerca per la ricerca.

**Comment by Bobanalist** [comment]
Avendo notato che nell'implementazione di ProdottoCRUD sono presenti Dto (RicercaDto) non richiesti e vista l'implementazione server su Spring,  prima di procedere chiediamo al Professore  @luca-lezzerini  maggiori requisiti sul campo di ricerca della Home Page.

**Comment by luca-lezzerini** [comment]
Create un DTO apposito (ad esempio SearchCriteriaHomePageDto che contiene la stringa da usare come chiave di ricerca.
La ricerca deve avvenire per chiave parziale per codice e descrizione prodotto.
Quindi verranno recuperati tutti i record che hanno o una parte del codice o del prodotto uguale alla stringa (unica) fornita.

**Comment by Ramello83** [comment]
In prodotti la ricerca aviene per chiave parziale su descrizione e codice. già tutto implementato. RicercaDto è stato creato proprio per questo motivo vista la necessità di trasportare una stringa per la richiesta di ricerca che non era ne un codice ne una descrizione, ma solo una parola chiave.  Il tutto per una maggiore leggibilità e riuso del codice. Come scritto precedentemente ne lato client si può usare il service prodotto per fare la ricerca nella home.

**Comment by Ramello83** [comment]
Visto che si tratta in tutti i casi di fare una ricerca per parola chiave completa o parziale non vedo il motivo di creare un DTO per ogni settore o pagina. Si potrebbe solo Rinominare RicecaDto in SearchCriteriaStringDto. per migliore lettura e usare sempre lo stesso Dto per tutte le ricerche con stringa.

**Comment by Ramello83** [comment]
Sistemati alcuni bug bd2969f8d41b672285c6101d0581c538a2ffb2e6
