### ISSUE TITLE
Creare Component prodotto

### ISSUE THREAD

**Issue by gianmarcopetrillo** [luca-lezzerini/ecomm-jpr-02#48]
Abbiamo bisogno di creare il component prodotto, è possibile??

**Comment by CatiaNiccolai** [comment]
Sono in attesa di conferma da parte di Giulio, ti avviso quanto prima

**Comment by CatiaNiccolai** [comment]
Gianmarco puoi procedere, attendo tua conferma per la chiusura del ticket

**Comment by gianmarcopetrillo** [comment]
Fatto, grazie!! 9d04df0cfa8944fa60188adb5737a8ff1b0d2e38
