### ISSUE TITLE
creazione component offerta

### ISSUE THREAD

**Issue by Giulio794** [luca-lezzerini/ecomm-jpr-02#49]
Devo creare component offerta, quando posso?

**Comment by CatiaNiccolai** [comment]
Giulio puoi farlo adesso? Altrimenti ti metto in coda

**Comment by Giulio794** [comment]
Fatto, grazie 30678692a5126ef94438e716621e8a6b0fb890c0
a775ee08964c32eb976100c00c9349a989c3a068
