### ISSUE TITLE
Richiesta di Controllo dell'uso corretto del linguaggio BPMN & UML

### ISSUE THREAD

**Issue by Ramello83** [luca-lezzerini/ecomm-jpr-02#5]
Salve. 
Abbiamo finito il primo diagramma di collaborazione. Ci piacerebbe sapere se abbiamo interpretato bene l'uso dei formalismi del linguaggio. Grazie.

**Comment by luca-lezzerini** [comment]
Mi può allegare al ticket il diagramma, possibilmente in formato PNG o similare? Grazie

**Comment by luca-lezzerini** [comment]
![Coreografie principali](https://user-images.githubusercontent.com/47611629/86888776-087dae00-c0fb-11ea-949d-1fa9c6c3892f.png)

**Comment by Ramello83** [comment]
![Processo](https://user-images.githubusercontent.com/67779342/86889269-c6a13780-c0fb-11ea-82c1-44c792280049.png)

**Comment by luca-lezzerini** [comment]
Il diagramma è stato rivisto in aula e quindi considero il ticket chiuso
