### ISSUE TITLE
Impostazione lato Server crud taglia

### ISSUE THREAD

**Issue by Francesco-bit** [luca-lezzerini/ecomm-jpr-02#50]
In riferimento al ticket #44 , impostare l`implementazione del lato server necessaria.

**Comment by Francesco-bit** [comment]
Commit fe26c82e3d9cef49eb363082aceaac6b9794a7ad

**Comment by Francesco-bit** [comment]
Modifiche apportate alle Entity. Commit 2f124999844070d578ae060785bab73a083faffc

**Comment by Giuseppe211** [comment]
ulteriori modifiche apportate. Commit 3494a4c91b4226342c9dae6faf9a0b587576a1f3

**Comment by Francesco-bit** [comment]
Modifiche al DTO. Commit 3b0f46d0305b0f4384493b4f643d0f9974738b7d
