### ISSUE TITLE
Impostare lato Client crud Taglia

### ISSUE THREAD

**Issue by Francesco-bit** [luca-lezzerini/ecomm-jpr-02#51]
In riferimento al ticket #44 , impostare l`implementazione del lato client necessaria.

**Comment by Francesco-bit** [comment]
Iniziata lavorazione. Commit 8cfd61a3744c4810e01d82a5e2c4f25838ce5fcc

**Comment by Francesco-bit** [comment]
Avanzamento lavorazione. Commit eee24ab8c10ccde7bf17737e488af8af397daa79

**Comment by Francesco-bit** [comment]
Commit 4a09bda533cfd3b7e1c015f7ede5c5526cbf23f1

**Comment by Francesco-bit** [comment]
Pronto per test. Commit fe26c82e3d9cef49eb363082aceaac6b9794a7ad

**Comment by Francesco-bit** [comment]
Modifiche a remove. modifiche alla view. Commit c59866737d5fb176ce693bc41f21c06069f16380 e 4c0c64ea18684baf46acdd033d73b122d293e50f

**Comment by Giuseppe211** [comment]
modifiche apportate. Commit 4439fc940650abcaf32b0b24b066cfca7ffcc380

**Comment by Giuseppe211** [comment]
stato visualizza impostato. Commit 221d31e441ee5fa19a7edc562aeef36b07622e36
