### ISSUE TITLE
problema con offertaServiceImpl in lato server

### ISSUE THREAD

**Issue by Giuseppe211** [luca-lezzerini/ecomm-jpr-02#52]
si dovrebbero risolvere alcuni errori in lato server (implementare il repOfferta)

**Comment by Ramello83** [comment]
Prova a vedere se riesco a risolvere subito

**Comment by Ramello83** [comment]
Problemi risolti e comitati a0b27d0d4bfa980fdd3628221cea4af22c0c290b

**Comment by Ramello83** [comment]
considero problema risolto chiudo
