### ISSUE TITLE
Aggiornamento routing.module.ts e app.module.ts

### ISSUE THREAD

**Issue by Bobanalist** [luca-lezzerini/ecomm-jpr-02#53]
Richiesta di aggiornamento per componente Spedizione nei due  module in oggetto

**Comment by CatiaNiccolai** [comment]
Puoi aggiornarli tu e poi avvisare sul gruppo prima di fare il commit.
fatto il commit possiamo chiudere questo ticket

**Comment by Bobanalist** [comment]
Aggiornato e chiudo
bfab934bdd9c7278ba541beb0afa2499ed2f35ae
