### ISSUE TITLE
Proposta per prodotti home o richiesta chiarimenti

### ISSUE THREAD

**Issue by Ramello83** [luca-lezzerini/ecomm-jpr-02#54]
nella home c'è la ricerca dei prodotti con quali criteri la implementiamo? io propongo descrizione.

**Comment by luca-lezzerini** [comment]
Non sono d'accordo. Proceda con codice e descrizione per chiave parziale (cioè basta una qualsiasi parte del codice o della descrizione). Se avete problemi con il repository perché non riuscite a scrivere il metodo con la query di ricerca, mi apra un altro ticket.

**Comment by Ramello83** [comment]
ok grazie per le ulteriori specifiche mi organizzo con chi ha presso in incarico la home, vedendo cosa riusciamo a fare in caso di problemi ho difficoltà provvederemo ad aprire un ticket.
