### ISSUE TITLE
Impostare nuova route

### ISSUE THREAD

**Issue by gianmarcopetrillo** [luca-lezzerini/ecomm-jpr-02#55]
Dovrei impostare una nuova route per prodotto-crud: 

{ path: 'prodotto-crud', component: ProdottoCrudComponent}

**Comment by Simoneval22** [comment]
ok nessuno sta modificando il file, procedi pure

**Comment by gianmarcopetrillo** [comment]
Fatto : 22557ba7ed69faf772275e891472e81765394630

**Comment by gianmarcopetrillo** [comment]
fatto : bf2b7d1c7b48f0ba727c7e72112ef5c0db8844fe (avevo messo lo sha errato)
