### ISSUE TITLE
Utente non loggato conclude checkout?

### ISSUE THREAD

**Issue by Francesco-bit** [luca-lezzerini/ecomm-jpr-02#6]
Avevamo notato e molto apprezzato sul sito IBS, durante le prime analisi, la possibilità per un cliente non registrato di concludere un acquisto. Le domandiamo se sia questa una funzione di cui tenere conto nella modellazione dei casi d`uso, e quindi da aggiungere alla coreografia del processo d`acquisto; o se non sia di interesse per il sito e-commerce in produzione. Grazie

**Comment by luca-lezzerini** [comment]
Un utente non autenticato non dovrebbe poter completare l'acquisto. La soluzione migliore è che, come si dirige al checkout, venga fatto autenticare.
