### ISSUE TITLE
Problema angular taglia

### ISSUE THREAD

**Issue by Ramello83** [luca-lezzerini/ecomm-jpr-02#60]
angular non compila sigla .  ERROR in src/app/taglia-crud/taglia-crud.component.ts(37,26): error TS2339: Property 'sigla' does not exist on type 'TagliaDto'.

**Comment by Francesco-bit** [comment]
Non trovo errore in taglia-crud.component.ts
Ma ho trovato il path in app-routing.module.ts con un typo.
A me va in esecuzione senza errori
![Console-in-run](https://user-images.githubusercontent.com/64693863/89555330-35170980-d810-11ea-9b77-f0a849b6a922.png)

**Comment by Ramello83** [comment]
risolto con ultimo pull
