### ISSUE TITLE
Uc Prodotti Fare service client e completare 

### ISSUE THREAD

**Issue by Ramello83** [luca-lezzerini/ecomm-jpr-02#62]
guardare UC colori b38f6c959c896d388679f76dc239723af7654c9f. 
Fare il service e modificare il codice

**Comment by Ramello83** [comment]
ho cambiato alcune cose da notare prima di procedere. Ho creato lato server un metodo multiparametro per la ricerca
3b79cb67ee229148e79ba98a1b72dfdf5ebbcea4

**Comment by gianmarcopetrillo** [comment]
Prodotto service implementato, manca la parte html, e poi passiamo alla fase di test.

**Comment by David-Michele** [comment]
Prodotto service completato e funzionante 
24bedd273f042d2be62cf9310d607bd92deafbcc

**Comment by Ramello83** [comment]
Fati piccolo cambiamenti ho provato e funziona tutto.
vi siete scordati nel tamplate di pulire l'input ricerca sfruttando il ritorno del metodo cerca del service. comunque tutto a posto 
commito i cambiamnti  e richiudo. 196a0ce8a5ad4567e08b7ea1a414640a94ca4386

**Comment by Ramello83** [comment]
chiudo
