### ISSUE TITLE
UC Oferta fare Service Client 

### ISSUE THREAD

**Issue by Ramello83** [luca-lezzerini/ecomm-jpr-02#63]
Guardare UCcolori b38f6c959c896d388679f76dc239723af7654c9f
Fare service lato cliente
e modificare codice Template e Component

**Comment by Ramello83** [comment]
ho cambiato alcune cose da notare prima di procedere. Ho creato lato server un metodo multiparametro per la ricerca
3b79cb67ee229148e79ba98a1b72dfdf5ebbcea4

**Comment by Tizioincognit0** [comment]
Parzialmente svolto con commit a8ca470f115938a6c06eeeb0ea43aef4c982b818. Non è stato possibile implementare “ricerca-dto.ts” in quanto causava il seguente errore in fase di compilazione su Visual Studio Code.
‘’’'
ERROR in dto/ricerca-dto.ts:1:27 - error TS2307: Cannot find module 'dns' or its corresponding type declarations.

1 import { SrvRecord } from 'dns';

**Comment by Tizioincognit0** [comment]
Ho provato ad aggiungere la ricerca multiparametro commentando quell’import nel commit 71eb819d935c9626d23689ec359e6e4f9485e70b.

**Comment by Tizioincognit0** [comment]
Effettuato test con database su aggiunta, modifica, rimozione e ricerca. Dopo aver effettuato alcune modifiche nel commit 8e1cda34e81dd3b965b505b446c5157a2cb36622, tutto sembra funzionare bene.

**Comment by Ramello83** [comment]
Fati piccolo cambiamenti, non ho capito bene perche ricerca non funzionava. ho provato e funzionava tutto.
vi siete scordati nel tamplate di pulire l'input ricerca sfruttando il ritorno del metodo cerca del service. comunque tutto a posto 
commito i cambiamnti  e richiudo. 196a0ce8a5ad4567e08b7ea1a414640a94ca4386

**Comment by Ramello83** [comment]
chiudo
