### ISSUE TITLE
Creazione RicercaDto Client e Server

### ISSUE THREAD

**Issue by CatiaNiccolai** [luca-lezzerini/ecomm-jpr-02#65]
Ho trovato che è stato creato RicercaDto  sia sul server che sul client (implementato nella ricerca dei prodotti), non presente sui requisiti e mai autorizzato da me. Vorrei capire se è una scelta personale o indicata da @luca-lezzerini. Non essendone a conoscenza sarebbe utile per tutti e per la migliore realizzazione del progetto comune, avere maggiori delucidazioni in merito.

**Comment by luca-lezzerini** [comment]
Io non autorizzo creazioni di componenti ma dico solo che vanno creati. Coordinarsi con lei è compito degli sviluppatori. Verifichi su Git chi l'ha creato e gli chieda delucidazioni.

**Comment by CatiaNiccolai** [comment]
Non ci sono ticket aperti per la creazione di RicercaDto.
@Ramello83 mi risulta che sia stato creato da te, puoi chiarire meglio a tutti la necessità e la funzione del Dto in oggetto? Ti sei confrontato con il professore o è stata una iniziativa tua?
Come mai non mi è stata chiesta l'autorizzazione alla creazione di questo componente?

**Comment by Ramello83** [comment]
Il componente interessava solo il lato prodotti. per poter fare una ricerca su chiave parziale su diversi attributi. Per rendere la semantica più comprensiva e riusabile. Per cambiare non ci vuole niente. Ma visto che anche la home page deve ricercare su prodotti una oggetto dedicato a trasporto della solo stringa di ricerca migliora la comprensione del tutto. legger #47

**Comment by CatiaNiccolai** [comment]
Si, abbiamo visto e utilizzato per la home il component RicercaDto. Il professore ci aveva suggerito una soluzione simile e quindi ci siamo agganciati a quanto già fatto da voi.
