### ISSUE TITLE
UC Crud Carrello e Anagrafiche

### ISSUE THREAD

**Issue by Bobanalist** [luca-lezzerini/ecomm-jpr-02#67]
Avendo definito la Home Page e l'implementazione del codice lato client e server per la ricerca dei prodotti abbiamo necessità di sviluppare l' UC Crud Carrello e Anagrafiche per poter terminare i collegamenti della Home Page.
Ci occorrono dettagli di analisi UML e UI

**Comment by luca-lezzerini** [comment]
Saranno rilasciati lunedì mattina.Sent from my Wiko W_C860Il 09 ago 2020 17:30, Bobanalist <notifications@github.com> ha scritto:

Avendo definito la Home Page e l'implementazione del codice lato client e server per la ricerca dei prodotti abbiamo necessità di sviluppare l' UC Crud Carrello e Anagrafiche per poter terminare i collegamenti della Home Page.

Ci occorrono dettagli di analisi UML e UI
