### ISSUE TITLE
Modificare e creare dto Colore

### ISSUE THREAD

**Issue by Ramello83** [luca-lezzerini/ecomm-jpr-02#69]
Creare dto lato server e client per trasmettere singolo e lista colore con token all interno. Modificare controller colore e service lato client

**Comment by Giulio794** [comment]
Creato DtoColore e DtoColori3ce92c87cea4f9c66973c5c867593638bf0fdaf0
7b89b970318ecf353a9192e56cb8419ab0e63993

**Comment by Ramello83** [comment]
9f7e5f7142090992ee126f522be629abf7695218

**Comment by Ramello83** [comment]
corezioni al codice sopra 31f41935282c2a3f1d4120d4f3e4c573f5a34ea0

**Comment by gianmarcopetrillo** [comment]
Completato colori, lato client e server, con inserimento passaggio Token

3da32811acbca3f7a3040bec5e57ef452bb3916b

**Comment by Ramello83** [comment]
Imposibile da testare fino a quando non saranno coretti errori su altri crud. a lettura il codice non presenta errori
