### ISSUE TITLE
Modificare e creare dto Prodotto

### ISSUE THREAD

**Issue by Ramello83** [luca-lezzerini/ecomm-jpr-02#70]
Creare dto lato server e client per trasmettere singolo e lista Prodotto con token all interno. Modificare controller e service di Prodotto lato client.

**Comment by Tizioincognit0** [comment]
Creati ProdottoDto e ListaProdottoDto lato server con commit f1c1e640fc1b2de8af88348ccc084f3e02fb1578.

**Comment by Tizioincognit0** [comment]
Creati ProdottoDto e ListaProdottoDto lato client; necessariamente si è dovuto procedere alla creazione anche di TokenDto e dei model Prodotto e Token nella cartella “model” con commit 072cff09d65e7a918bac398cc1a2fe7f693a9cee.

**Comment by Tizioincognit0** [comment]
Aggiunta gestione dei token a findProdottiByCodiceOrDescrizione lato server su controller e service con commit 75951a3f14b8f6746c0d6fa42ab0a8744febaf99.

**Comment by Tizioincognit0** [comment]
Aggiunta gestione dei token a listaProdotti lato server su controller con commit 0db981913cbea2285c0cce4c3ada64d2e8cf5475.

**Comment by Tizioincognit0** [comment]
Aggiunta la gestione dei token agli altri metodi del controller lato server con commit 2aab51bccb25201d33c707bf99b4f165fbe54114.

**Comment by Tizioincognit0** [comment]
Prima di procedere alla aggiunta della gestione dei token al service lato client, attendo che venga risolta l’issue #75.

**Comment by Tizioincognit0** [comment]
Diversificati “Prodotto” e “ProdottoDto” lato client con commit 214dd622143f8cd56b1a1a22690851ba962e1b2e.

**Comment by Tizioincognit0** [comment]
Diversificati “Prodotto” e “ProdottoDto” lato client con commit 214dd622143f8cd56b1a1a22690851ba962e1b2e.

**Comment by Tizioincognit0** [comment]
Diversificati “Prodotto” e “ProdottoDto” lato client con commit 214dd622143f8cd56b1a1a22690851ba962e1b2e.

**Comment by Tizioincognit0** [comment]
Apportate migliorie a “ProdottoController.java” con commit f1e807f849d55a79e85c884d1475e98a8c8ec482. Ora procederò alla gestione dei token sul service lato client.

**Comment by Tizioincognit0** [comment]
Completato con commit 967b861f0cf934f2a763984976b322f384b140d5 ma non ancora testato.

**Comment by Ramello83** [comment]
Imposibile da testare fino a quando non saranno coretti errori su altri crud. a lettura il codice non presenta errori

**Comment by Tizioincognit0** [comment]
Risolti problemi che impedivano l’accesso ai dati presenti sul con commit 331ad78c53579a8f4ad5477bdb9f8d7fc371f4cd. Dai test effettuati risulta che bisogna impedire che si possano aggiungere prodotti con i campi vuoti e bisogna fare in modo che il campo ricerca rimanga visualizzato anche dopo che sono stati trovati i risultati.

**Comment by Tizioincognit0** [comment]
Risolti problemi che impedivano l’accesso ai dati presenti sul con commit 331ad78. Test effettuati con successo.
