### ISSUE TITLE
Modificare e creare Dto Offerta

### ISSUE THREAD

**Issue by Ramello83** [luca-lezzerini/ecomm-jpr-02#71]
Creare dto lato server e client per trasmettere singolo e lista Offerta con token all interno. Modificare controller colore e service lato client

**Comment by gianmarcopetrillo** [comment]
Creato OffertaDto, ListaOfferteDto lato server:
d0f0670076b2803f5fcadc48b7e4afc0a304e0aa

**Comment by gianmarcopetrillo** [comment]
Controller fatto
7390e72814102b52f72854879a658850dd0f055e

**Comment by Ramello83** [comment]
Imposibile da testare fino a quando non saranno coretti errori su altri crud. a lettura il codice non presenta errori

**Comment by Tizioincognit0** [comment]
Gli altri errori sono stati corretti ed i test (antecedenti all'inizio della realizzazione dell'issue #84) non hanno riscontrato bug.
