### ISSUE TITLE
Richiesta modifica campi ID lato client

### ISSUE THREAD

**Issue by Bobanalist** [luca-lezzerini/ecomm-jpr-02#76]
Come da indicazione del Capo Progetto richiedo la modifica di tutti i campi ID lato client, da number a string sui DTO Categoria e Spedizione.

**Comment by CatiaNiccolai** [comment]
Autorizzato.
@luca-lezzerini Ogni gruppo dovrà fare le proprie o posso autorizzare Badessi a farle per tutto il progetto?

**Comment by Tizioincognit0** [comment]
Per “Prodotto”, “Offerta” e “Colore”.

**Comment by Tizioincognit0** [comment]
Eseguita modifica su “Prodotto” con commit 47175f3cc1a56299ea484d374901bac8486ff3fb.

**Comment by Tizioincognit0** [comment]
Eseguita modifica su “Offerta” e “Colore” con commit 9fc75c391d4c5363f9e4eb018c04eb726f7f297e.

**Comment by Tizioincognit0** [comment]
Eseguita modifica su “Offerta” e “Colore” con commit 7abce2588265dcff8d43d7ba83377f1c8914adca.

**Comment by Tizioincognit0** [comment]
Eseguita modifica su “Offerta” (con commit 9fc75c391d4c5363f9e4eb018c04eb726f7f297e) e “Colore” (con commit 7abce25).

**Comment by CatiaNiccolai** [comment]
Modifica effettuate sui Dto presenti
