### ISSUE TITLE
Metodo in token.service.ts da rimuovere

### ISSUE THREAD

**Issue by Bobanalist** [luca-lezzerini/ecomm-jpr-02#77]
Come da indicazione del Capo Progetto richiedo l'eliminazione del metodo controllaToken() in quanto superfluo.

**Comment by CatiaNiccolai** [comment]
Assegno a @Ramello83 la modifica in oggetto.
Effettuala la modifica chiudere direttamente il ticket

**Comment by Ramello83** [comment]
Rimosso 969a9d8dae0227e39376836c8ad6302bcef70bb7
