### ISSUE TITLE
necesita di creare cartella model 

### ISSUE THREAD

**Issue by Ramello83** [luca-lezzerini/ecomm-jpr-02#78]
Parlando con il capo progetto si è visto la necesita di dividere i dto dai model sul lato client. In maniera di avere dto composti dalla classe token e dalla classe o lista di classi specifiche del dto. chiedo autorizzazione nel procedere.

**Comment by CatiaNiccolai** [comment]
Creata già da Badessi, richiedo il committente ma il codice di categoria non compilerà

**Comment by Bobanalist** [comment]
Creata 
SHA cb5dd95ed234698f89c2ccf774430c07ad40e015
