### ISSUE TITLE
Link riferimento implementazione Optional

### ISSUE THREAD

**Issue by CatiaNiccolai** [luca-lezzerini/ecomm-jpr-02#79]
Professore non ci ha più inviato il link che stamattina ci ha consigliato di guardare per capire meglio come utilizzare correttamente l'Optional, quando può ce lo manda?

**Comment by gianmarcopetrillo** [comment]
Il professore oggi ha mandato questo link riguardante gli Optional..
Forse è proprio quello a cui fai riferimento!!!

https://codingjam.it/java8-gli-optional/

**Comment by CatiaNiccolai** [comment]
@gianmarcopetrillo Si esatto, io non lo vedo... come l'altro che mi ha girato Marco :) grazie!!!
