### ISSUE TITLE
Richiesta chiarimento sul pagamento per gli Use Case

### ISSUE THREAD

**Issue by Bobanalist** [luca-lezzerini/ecomm-jpr-02#8]
Avremmo bisogno di capire se nel diagramma delle coreografie, quella relativa a cliente-gestore pagamento (che descrive il pagamento), si intende il gestore pagamento dell'amministrazione (quindi scrittura prima nota ecc..), oppure il Gateway della banca. Questo perché nella logica del portale ecommerce il pagamento si effettua tra cliente e gateway di banca. 
![UseCase](https://user-images.githubusercontent.com/67779690/86901883-7cc14d00-c10d-11ea-8992-634862822297.PNG)

**Comment by luca-lezzerini** [comment]
Il gestore pagamenti è un partecipante software e corrisponde al gateway di pagamento della banca, nel caso di pagamento con carta. Al momento non è necessario prevedere forme di pagamento di tipo diverso dalla carta.
