### ISSUE TITLE
Mal funzionamento di Prodotto, Colore e Offerta

### ISSUE THREAD

**Issue by Ramello83** [luca-lezzerini/ecomm-jpr-02#84]
Con le modifiche apportate ieri si è avuta una regressione sul funzionamento.

**Comment by Ramello83** [comment]
Prodotto sistemato e funzionante 331ad78c53579a8f4ad5477bdb9f8d7fc371f4cd

**Comment by Ramello83** [comment]
Sistemato colori funzionante b27cbf9adf206309180e777fa082688e6b762e13

**Comment by Ramello83** [comment]
Il ticket non viene chiuso perche colori presenta una stranezza.

**Comment by Tizioincognit0** [comment]
Mal funzionamento e stranezza di Colore risolti con commit 478f27fdffafe2696db434aaea4094b0cb808ea6.
