### ISSUE TITLE
Malfunzionamento Imballo

### ISSUE THREAD

**Issue by CatiaNiccolai** [luca-lezzerini/ecomm-jpr-02#87]
Su imballo la modifica va in crash

**Comment by CatiaNiccolai** [comment]
modifica effettuata

**Comment by luca-lezzerini** [comment]
Perché mi ha assegnato questo ticket?

**Comment by CatiaNiccolai** [comment]
Buonasera Professore!
Sinceramente non me lo ricordo… credo risalga a una delle ultime lezioni sul debug del project work

**Comment by luca-lezzerini** [comment]
Buonasera Niccolai, non me lo ha assegnato lei ma TizioIncognito.

**Comment by Tizioincognit0** [comment]
Sí, lo avevo assegnato io per sbaglio.

**Comment by luca-lezzerini** [comment]
Ok, chi sei? Come mai stai usando questo sistema? Se hai bisogno di esercitarti per trovare lavoro posso darti un progetto specifico da fare, un esercizio didattico ma finalizzato a consolidare determinate conoscenze.
Buon giornata
