### ISSUE TITLE
Completare lato server e lato client Imballo-crud

### ISSUE THREAD

**Issue by Giuseppe211** [luca-lezzerini/ecomm-jpr-02#88]

**Comment by Giuseppe211** [comment]
aggiornamenti apportati. Commit 19dd9c2ba7b825d4dc28e608f164d5b0529104e7

**Comment by Tizioincognit0** [comment]
Lato server completato con commit f368413. Ulteriori modifiche al lato client potranno essere segnalate nell'issue #37.
