### ISSUE TITLE
Vedere bug in Colori

### ISSUE THREAD

**Issue by gianmarcopetrillo** [luca-lezzerini/ecomm-jpr-02#89]
Colori non mostra la lista, sembra ricevere la risposta giusta (vedere in console client, network -> lista-colori -> response ,da prima il token e poi la lista) e anche la query sembra fatta bene in console lato server. 
Aggiungi funziona, modifica ed elimina non sono riuscito a testarli.

**Comment by Ramello83** [comment]
Sistemato colori funzionante b27cbf9

**Comment by Ramello83** [comment]
colori presenta una stranezza #90
