### ISSUE TITLE
Stranezza in colore

### ISSUE THREAD

**Issue by Ramello83** [luca-lezzerini/ecomm-jpr-02#90]
Facendo il debug di Colori è uscita una stranezza.
Risolti vari errori l'anagrafe colori non funzionava, il server funzionava bene e i dati arrivavano al client verificato da console. ma i nomi erano diversi sia il dto che gli atributi. Fatta una prova usando il nome degli atributi di console funziona tutto ma giustamente angular dice che quel attributo non e presente nel dto. non sono riuscito a capire da cosa dipende. Mi piacerebbe discuterne domani o meglio oggi Pomeriggio. Buonagiornata.

**Comment by Tizioincognit0** [comment]
Aggiungo che queste stranezze impediscono la compilazione lato client.
`ERROR in src/app/colori.service.ts:22:101 - error TS2339: Property 'listaColori' does not exist on type 'ColoriDto'.

22     const sub: Subscription = oss.subscribe(risp => { this.listaDto = risp; this.listaColori = risp.listaColori;
                                                                                                       ~~~~~~~~~~~
src/app/colori.service.ts:24:24 - error TS2339: Property 'listaColori' does not exist on type 'ColoriDto'.

24       console.log(risp.listaColori); });
                          ~~~~~~~~~~~
src/app/colori.service.ts:40:81 - error TS2339: Property 'listaColori' does not exist on type 'ColoriDto'.

40       const sub: Subscription = oss.subscribe(risp => { this.listaColori = risp.listaColori ; this.srvToken.setToken(this.listaDto.token); });
`

**Comment by Tizioincognit0** [comment]
Nel tentare di risolvere questa stranezza si erano creati dei problemi che impedivano la compilazione lato client. Essi sono stati risolti con commit 545e7c6f0b78de2e92ae979ea8c105f86c93e222.

**Comment by Ramello83** [comment]
gli errori su detti servivano a fare funzionare colori. anche se angular dava errori comunque tutto funzionava

**Comment by Ramello83** [comment]
errori ripristinati f8fde1042335559240c059c506571c95777db304
trovato errore in prodotti da console ma tutto funziona.

**Comment by Ramello83** [comment]
prodotto update risolto fd1197d8b5bd52d75c4ef7b780ab4e8489eb393e

**Comment by Tizioincognit0** [comment]
Stranezza risolta con commit 478f27fdffafe2696db434aaea4094b0cb808ea6.
