### ISSUE TITLE
Refactor per inserimento token in Taglia e Taglia CRUD

### ISSUE THREAD

**Issue by Francesco-bit** [luca-lezzerini/ecomm-jpr-02#91]
Modifiche e refactor per inserimento token in Taglia. Client e Server.

**Comment by Francesco-bit** [comment]
Modifiche da testare. Commit 05ada6ff0eb7eaa3832f870c128fbc45bc90a23e

**Comment by Simoneval22** [comment]
Aggiornamento Taglia lato client 83ae40db8d14f7c30277812712b33b6ff984b38c

**Comment by Francesco-bit** [comment]
Commit fb98763f99e337274218d2bd7ed665a8e4281a53

**Comment by Francesco-bit** [comment]
Da completare service. Token presente ma lista nella lambda gestita non uniformemente.
