### ISSUE TITLE
Creazione cartelle per entity e service lato client

### ISSUE THREAD

**Issue by Francesco-bit** [luca-lezzerini/ecomm-jpr-02#95]

**Comment by Francesco-bit** [comment]
Cartella entity inutile. Gia presente la cartella model. Refactor necessario per TAGLIA e IMBALLO.

**Comment by Giuseppe211** [comment]
cartella entity eliminata e classi spostate nella cartella model. Commit ff8fa642e511bf5b5b4d9559f159d7fd8e7b99ad

**Comment by Tizioincognit0** [comment]
Fatto con commit https://github.com/luca-lezzerini/ecomm-jpr-02/commit/a62a1e785662a56aff8733c2081b41b4b4f7de01.
