### ISSUE TITLE
Refactor per inserimento token in Imballo e Imballo CRUD

### ISSUE THREAD

**Issue by Francesco-bit** [luca-lezzerini/ecomm-jpr-02#96]

**Comment by Francesco-bit** [comment]
Da completare service. Token non sempre presente e lista nella lambda gestita non uniformemente.

**Comment by Giuseppe211** [comment]
Completato. Commit ff8fa642e511bf5b5b4d9559f159d7fd8e7b99ad

**Comment by Francesco-bit** [comment]
Lista nei vari metodi del service da modificare.

**Comment by Tizioincognit0** [comment]
Completato con commit f368413.
