### ISSUE TITLE
Chiarimento necessario per Visualizza state

### ISSUE THREAD

**Issue by FrancescoRomanelli** [luca-lezzerini/ecomm-jpr-02#98]
![Cattura](https://user-images.githubusercontent.com/64693863/92586019-ff919000-f295-11ea-912f-0c56a10df8ed.PNG)

Dagli schemi di progettazione capisco che nello state visualizza sia previsto che la tabella e il form di ricerca rimangano visibili. Ieri, martedi 8, però durante il debugging avevamo preso la strada opposta. Fermo restando che in assenza di record la tabella non deve mai essere visualizzata nella pagina, come procediamo nell`implementazione?

**Comment by Tizioincognit0** [comment]
Quello indicato con "formDati" non è il form di ricerca bensì il form per la visualizzazione dei dati di un determinato oggetto. Dunque non vi è alcuna incongruenza.
