### ISSUE TITLE
Implementare UC Associazione Prodotto con Offerta

### ISSUE THREAD

**Issue by luca-lezzerini** [luca-lezzerini/ecomm-jpr-02#99]

**Comment by gianmarcopetrillo** [comment]
Aggiunta annotation OneToMany in offerta
 fcbbf9fcb158637567bda5c9a7244086eae8fcbd

**Comment by gianmarcopetrillo** [comment]
Aggiunta annotation OneToMany in offerta
8846a123c66d8c602317d02fe90085eba2d6da7a

**Comment by Tizioincognit0** [comment]
Terminata con commit https://github.com/luca-lezzerini/ecomm-jpr-02/commit/007834c12841837161706a343962271f732261b2.
